---
name: CI/CD Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate YAML Files
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint .

      - name: Hola
        run: echo "Hola CI y CD"





