---
name: CI/CD Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate prueba.yml
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint .github/workflows/prueba.yml || true
      - name: Display yamllint result
        run: echo "Resultados de yamllint:"
        run: |
          yamllint .github/workflows/prueba.yml
      - name: Hola
        run: echo "Hola CI y CD"

